version: "3"
services:
#  mongodb:
#    image: mongo
#    ports:
#      - '27017:27017'
#    volumes:
#      - db:/data/db
#    networks:
#      - app
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
#    depends_on: [mongodb]

    networks:
      - app


  users:
    build: ./users-api
    ports:
      - '8080:3000'
#    depends_on: [ mongodb ]
    volumes:
      - logs:/app/users

    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://qwerty:2913454@mycluster.sqhohp9.mongodb.net/?retryWrites=true&w=majority&appName=MyCluster'
      AUTH_API_ADDRESS: 'auth:3000'

    networks:
      - app

volumes:
  logs:
  db:

networks:
  app:
    driver: bridge
